//
//  WKWebViewControllerWKUIDelegate.swift
//  Browser
//
//  Created by Leonardo Larrañaga on 2/2/25.
//

import WebKit

/// WKWebView controller with WKUIDelegate conformance
extension WKWebViewController: WKUIDelegate {
    /// Handles OK alerts generated by JavaScript
    func webView(_ webView: WKWebView, runJavaScriptAlertPanelWithMessage message: String, initiatedByFrame frame: WKFrameInfo, completionHandler: @escaping @MainActor () -> Void) {
        let website = frame.request.url?.host() ?? "Website"
        
        let messageTextField = NSTextField(labelWithString: message)
        messageTextField.isSelectable = true
        
        let alert = NSAlert()
        alert.messageText = "\(website) says:"
        alert.accessoryView = messageTextField
        alert.addButton(withTitle: "OK")
        
        alert.runModal()
        completionHandler()
    }
    
    /// Handles confirm dialogs (OK, Cancel) generated by JavaScript
    func webView(_ webView: WKWebView, runJavaScriptConfirmPanelWithMessage message: String, initiatedByFrame frame: WKFrameInfo, completionHandler: @escaping @MainActor (Bool) -> Void) {
        let website = frame.request.url?.host() ?? "Website"
        
        let messageTextField = NSTextField(labelWithString: message)
        messageTextField.isSelectable = true
        
        let alert = NSAlert()
        alert.messageText = "\(website) says:"
        alert.accessoryView = messageTextField
        alert.addButton(withTitle: "OK")
        alert.addButton(withTitle: "Cancel")
        
        let response = alert.runModal()
        print(response == .alertFirstButtonReturn ? "OK" : "Cancel")
        completionHandler(response == .alertFirstButtonReturn)
    }
    
    /// Handles prompts (text input) generated by JavaScript
    func webView(_ webView: WKWebView, runJavaScriptTextInputPanelWithPrompt prompt: String, defaultText: String?, initiatedByFrame frame: WKFrameInfo, completionHandler: @escaping @MainActor (String?) -> Void) {
        let website = frame.request.url?.host() ?? "Website"
        
        let messageTextField = NSTextField(labelWithString: prompt)
        messageTextField.isSelectable = true
        
        let inputTextField = NSTextField(string: defaultText ?? "")
        
        let accessoryView = NSStackView(views: [messageTextField, inputTextField])
        accessoryView.orientation = .vertical
        accessoryView.spacing = 8
        accessoryView.alignment = .centerX
        accessoryView.distribution = .equalCentering
        accessoryView.frame.size.width = 400
        accessoryView.frame.size.height = messageTextField.frame.size.height + inputTextField.frame.size.height + 8
        
        NSLayoutConstraint.activate([
            inputTextField.widthAnchor.constraint(equalToConstant: 300),
            accessoryView.widthAnchor.constraint(equalToConstant: 400)
        ])
        
        let alert = NSAlert()
        alert.messageText = "\(website) says:"
        alert.accessoryView = accessoryView
        
        alert.addButton(withTitle: "OK")
        alert.addButton(withTitle: "Cancel")
        
        let response = alert.runModal()
        completionHandler(response == .alertFirstButtonReturn ? inputTextField.stringValue : nil)
    }
    
    func webView(_ webView: WKWebView, requestMediaCapturePermissionFor origin: WKSecurityOrigin, initiatedByFrame frame: WKFrameInfo, type: WKMediaCaptureType, decisionHandler: @escaping @MainActor (WKPermissionDecision) -> Void) {
        let host = origin.host

        let types: [SitePermissionType]
        switch type {
        case .camera: types = [.camera]
        case .microphone: types = [.microphone]
        case .cameraAndMicrophone: types = [.camera, .microphone]
        @unknown default: types = []
        }

        let decisions = types.map { SitePermissionStore.shared.decision(host: host, type: $0) }

        if decisions.contains(.deny) {
            decisionHandler(.deny)
        } else if !decisions.isEmpty && decisions.allSatisfy({ $0 == .allow }) {
            decisionHandler(.grant)
        } else {
            decisionHandler(.prompt)
        }
    }

    /// Handles file uploads
    func webView(_ webView: WKWebView, runOpenPanelWith parameters: WKOpenPanelParameters, initiatedByFrame frame: WKFrameInfo, completionHandler: @escaping @MainActor ([URL]?) -> Void) {
        let openPanel = NSOpenPanel()
        
        openPanel.allowsMultipleSelection = parameters.allowsMultipleSelection
        openPanel.canChooseDirectories = parameters.allowsDirectories
        
        openPanel.begin { response in
            if response == .OK {
                completionHandler(openPanel.urls)
            } else {
                completionHandler(nil)
            }
        }
    }
}
